# Generated by Django 4.2.6 on 2023-10-31 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('status', models.IntegerField(choices=[(0, 'En espera'), (1, 'Aceptado'), (2, 'Rechazado'), (3, 'Error')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
